# Generated by Django 2.2.7 on 2019-12-22 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='acc_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='model/'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='train_data',
            field=models.FileField(blank=True, null=True, upload_to='textdata/'),
        ),
    ]
