# Generated by Django 2.2.7 on 2019-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('learningdata', models.FileField(upload_to='')),
                ('learningmodel', models.CharField(max_length=100)),
            ],
        ),
    ]
